### ISSUE TITLE
esc not loading

### ISSUE THREAD

**Issue by wRONgR** [strengejacke/esc#1]
Hi Daniel & all,
I tried to load the esc package and get the following error message: 
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘sjmisc’ 2.0.0 is being loaded, but >= 2.5.0 is required
In addition: Warning message:
package ‘esc’ was built under R version 3.3.3 
Error: package or namespace load failed for ‘esc’

Any suggestions for what might be going on? I am relatively new to R, so still trying to work my way around issues.
Many thanks in advance
ron

**Comment by wRONgR** [comment]
I removed the sjmisc package manually and then reinstalled 'esc'. It is now working fine. Not sure why the updating of sjmisc during the installation of esc did not work though.

**Comment by strengejacke** [comment]
Ok, but this issue is solved?
