### ISSUE TITLE
Calling && or || with either argument of length greater than one

### ISSUE THREAD

**Issue by pgonzaleze** [strengejacke/esc#12]
I recently reviewed an old script but now I got this error when I run it on a new computer with R version 4.3.1:

Error in missing(grp1sd) || is.null(grp1sd) || is.na(grp1sd) : 
  'length = 59' in coercion to 'logical(1)'

I wonder if the error is related to this what is said here https://github.com/kaz-yos/tableone/issues/93:
"Message from the CRAN maintainer:

NEWS for R-devel has

• Calling && or || with either argument of length greater than one
now gives a warning (which it is intended will become an error)."

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by pgonzaleze** [comment]
I forgot to attach the output; after running the sample code I get this error: 

Error in missing(grp1sd) || is.null(grp1sd) || is.na(grp1sd) : 
  'length = 3' in coercion to 'logical(1)'

The same code run perfectly last year (using R version 3.6.1), but now I get this error (using 4.3.1)

**Comment by gl-007** [comment]
My team ran into the same problem when upgrading to R 4.3.1. The issue seems to be the checks is.na() in lines 54, 55 and 56 in the function. I did a quick hot fix via any(is.na()) which avoids that error, but not sure if that is the desired behaviour.

**Comment by pgonzaleze** [comment]
Thanks @gl-007, I tried it and I got this error, do you happen to know how to solve this?: 
Error in esc_generic(es = NA, v = NA, es.type = es.type, grp1n = NA, grp2n = NA,  : 
  could not find function "esc_generic"
In addition: Warning message:
Either `totalsd` or both `grp1sd` and `grp2sd` must be specified.
