### ISSUE TITLE
esc_rpb does not output r

### ISSUE THREAD

**Issue by dwhancock** [strengejacke/esc#4]
It says on the documentation that for esc_rpb I can ask it to give me the effect size r in the output.  When I try it, it says that is has to be any of the other types listed (d, g, logodds, etc).  the default for it seems to be to spit out a cohen's d, which isn't what I thought the default would be.  either way, it'd be nice if it would allow me to get output with the effect size as an r.

**Comment by strengejacke** [comment]
The function states _compute effect size **from** Point-Biserial Correlation_, thus, the effect-size `r` is the input, not the output.

**Comment by dwhancock** [comment]
In the arguments section under esc_rpb, it lists r as an output type under es.type.  In the linked webpage calculator, you can enter the r and n and it gives you back out the r and range and variability.  I wanted to get the standard error of the correlation coefficient, so I was using this function with r and n as inputs, hoping to get r and se as outputs.  Is there another function that does this, which more closely mirrors that of the webpage (r into r, with standard error, based on sample size)?
